##
## EPITECH PROJECT, 2025
## 103cipher
## File description:
## Makefile
##

all:
	@cp 103cipher.py 103cipher
	@chmod 775 103cipher

epiclang:
	epiclang $(SRC)

clean:
	@rm -f 103cipher.o
	@rm -f *~
	@rm -f *#
	@rm -f *.a
	@rm -f targets.log
	@rm -f dryrun.log
	@rm -f *.pch
	@rm -f 103cipher

fclean: clean

re: fclean all

.PHONY: all clean fclean re
